import type { Product, ProductType } from "../types/types";

export const allProducts: Product[] = [
  { id: 1, name: "Яблоко", typeId: 1 },
  { id: 2, name: "Груша", typeId: 1 },
  { id: 3, name: "Банан", typeId: 1 },
  { id: 4, name: "Апельсин", typeId: 1 },
  { id: 5, name: "Персик", typeId: 1 },
  { id: 6, name: "Хлеб", typeId: 2 },
  { id: 7, name: "Багет", typeId: 2 },
  { id: 8, name: "Круассан", typeId: 2 },
  { id: 9, name: "Булочка с корицей", typeId: 2 },
  { id: 10, name: "Молоко", typeId: 3 },
  { id: 11, name: "Сыр", typeId: 3 },
  { id: 12, name: "Йогурт", typeId: 3 },
  { id: 13, name: "Кефир", typeId: 3 },
  { id: 14, name: "Шоколад", typeId: 4 },
  { id: 15, name: "Печенье", typeId: 4 },
  { id: 16, name: "Торт", typeId: 4 },
  { id: 17, name: "Конфеты", typeId: 4 },
  { id: 18, name: "Говядина", typeId: 5 },
  { id: 19, name: "Курица", typeId: 5 },
  { id: 20, name: "Свинина", typeId: 5 },
  { id: 21, name: "Рыба", typeId: 5 },
  { id: 22, name: "Помидор", typeId: 6 },
  { id: 23, name: "Огурец", typeId: 6 },
  { id: 24, name: "Картофель", typeId: 6 },
  { id: 25, name: "Морковь", typeId: 6 },
  { id: 26, name: "Минеральная вода", typeId: 7 },
  { id: 27, name: "Сок яблочный", typeId: 7 },
  { id: 28, name: "Сок апельсиновый", typeId: 7 },
  { id: 29, name: "Кофе", typeId: 7 },
  { id: 30, name: "Чай", typeId: 7 },
];

export const productTypes: ProductType[] = [
  { id: 1, name: "Фрукты" },
  { id: 2, name: "Выпечка" },
  { id: 3, name: "Молочные продукты" },
  { id: 4, name: "Сладости" },
  { id: 5, name: "Мясо и рыба" },
  { id: 6, name: "Овощи" },
  { id: 7, name: "Напитки" },
];
